// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input vdcda36,
 input vclk,
 output [1:0] vbd2888,
 output vc6413b,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = vdcda36;
 assign vbd2888 = w2;
 assign vc6413b = w3;
 assign w4 = vclk;
 assign w5 = vclk;
 assign w5 = w4;
 vaa64b4 vcf94a7 (
  .v3dc29f(w1),
  .ve58ff0(w2),
  .vd1077b(w3),
  .v6dda25(w4)
 );
 vf92dfc vc821c3 (
  .vd9601b(w0),
  .v64879c(w1),
  .vfde3d7(w5)
 );
 assign vinit = 5'b00000;
endmodule

//---- Top entity
module vaa64b4 (
 input v6dda25,
 input v3dc29f,
 output [1:0] ve58ff0,
 output vd1077b
);
 wire w0;
 wire [0:1] w1;
 wire w2;
 wire [0:1] w3;
 wire [0:1] w4;
 wire w5;
 assign w0 = v3dc29f;
 assign w2 = v6dda25;
 assign ve58ff0 = w3;
 assign vd1077b = w5;
 assign w4 = w3;
 v92c002 v701d7a (
  .v8642da(w1),
  .v2ca089(w4),
  .v4642b6(w5)
 );
 vbdd2a8 vf2bbd0 (
  .v23125b(w0),
  .v8e4159(w1),
  .v9e41c3(w2),
  .ve6fa88(w3)
 );
endmodule

//---------------------------------------------------
//-- Counter-x02
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Counter-x02: 2-bits counter
//---------------------------------------------------
//---- Top entity
module v92c002 #(
 parameter v6c5139 = 1
) (
 input [1:0] v2ca089,
 output v4642b6,
 output [1:0] v8642da
);
 localparam p3 = v6c5139;
 wire w0;
 wire [0:1] w1;
 wire [0:1] w2;
 assign v4642b6 = w0;
 assign w1 = v2ca089;
 assign v8642da = w2;
 vc9ab7e #(
  .vd73390(p3)
 ) v948eeb (
  .v4642b6(w0),
  .v710efa(w1),
  .vc98ca1(w2)
 );
endmodule

//---------------------------------------------------
//-- Inc1-2bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-2bit: Increment a 2-bits number by one
//---------------------------------------------------
//---- Top entity
module vc9ab7e #(
 parameter vd73390 = 0
) (
 input [1:0] v710efa,
 output v4642b6,
 output [1:0] vc98ca1
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:1] w2;
 wire [0:1] w3;
 wire [0:1] w4;
 assign v4642b6 = w0;
 assign w3 = v710efa;
 assign vc98ca1 = w4;
 vb6461b #(
  .vc5c8ea(p1)
 ) v0b22e9 (
  .vb24d16(w2)
 );
 vcea0c2 v324058 (
  .v4642b6(w0),
  .v70abdd(w2),
  .v37c646(w3),
  .ve8a221(w4)
 );
endmodule

//---------------------------------------------------
//-- AdderK-2bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-2bit: Adder of 2-bit operand and 2-bit constant
//---------------------------------------------------
//---- Top entity
module vb6461b #(
 parameter vc5c8ea = 0
) (
 output [1:0] vb24d16
);
 localparam p0 = vc5c8ea;
 wire [0:1] w1;
 assign vb24d16 = w1;
 vb6461b_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 2-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 2-bits generic constant (0,1,2,3)
//---------------------------------------------------

module vb6461b_v465065 #(
 parameter VALUE = 0
) (
 output [1:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vcea0c2 (
 input [1:0] v70abdd,
 input [1:0] v37c646,
 output v4642b6,
 output [1:0] ve8a221
);
 wire [0:1] w0;
 wire [0:1] w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:1] w10;
 assign w0 = v70abdd;
 assign w1 = v37c646;
 assign v4642b6 = w7;
 assign ve8a221 = w10;
 v0dbcb9 v9d3ce0 (
  .v8b19dd(w0),
  .v64d863(w3),
  .v3f8943(w6)
 );
 v0dbcb9 vd20c1c (
  .v8b19dd(w1),
  .v64d863(w2),
  .v3f8943(w5)
 );
 v1ea21d vdbe125 (
  .v82de4f(w2),
  .v27dec4(w3),
  .v4642b6(w4),
  .v8e8a67(w9)
 );
 vad119b vb8ad86 (
  .v0ef266(w4),
  .v82de4f(w5),
  .v27dec4(w6),
  .v4642b6(w7),
  .v8e8a67(w8)
 );
 v80ac84 v5e602a (
  .vee8a83(w8),
  .v03aaf0(w9),
  .v67a3fc(w10)
 );
endmodule

//---------------------------------------------------
//-- Adder-2bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-2bits: Adder of two operands of 2 bits
//---------------------------------------------------
//---- Top entity
module v0dbcb9 (
 input [1:0] v8b19dd,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = v8b19dd;
 v0dbcb9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus2-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus2-Split-all: Split the 2-bits bus into two wires
//---------------------------------------------------

module v0dbcb9_v9a2a06 (
 input [1:0] i,
 output o1,
 output o0
);
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-1bit: Adder of two operands of 1 bit
//---------------------------------------------------
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
//---------------------------------------------------
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: two bits input xor gate
//---------------------------------------------------

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v80ac84 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 v80ac84_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus2-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus2-Join-all: Joint two wires into a 2-bits Bus
//---------------------------------------------------

module v80ac84_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vbdd2a8 #(
 parameter v438624 = 0
) (
 input v9e41c3,
 input [1:0] v8e4159,
 input v23125b,
 output [1:0] ve6fa88
);
 localparam p0 = v438624;
 wire w1;
 wire w2;
 wire [0:1] w3;
 wire [0:1] w4;
 assign w1 = v9e41c3;
 assign w2 = v23125b;
 assign w3 = v8e4159;
 assign ve6fa88 = w4;
 vbdd2a8_vd976a7 #(
  .INI(p0)
 ) vd976a7 (
  .clk(w1),
  .load(w2),
  .d(w3),
  .q(w4)
 );
endmodule

//---------------------------------------------------
//-- 02-Reg
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 02-Reg: 2 bits Register. Verilog implementation
//---------------------------------------------------

module vbdd2a8_vd976a7 #(
 parameter INI = 0
) (
 input clk,
 input [1:0] d,
 input load,
 output [1:0] q
);
 //-- Generic register
 //-- Number of bits
 localparam N = 2;
 
 //-- Initial value
 reg [N-1:0] qi = INI;
 
 always @(posedge clk)
 
   //-- The value is load only if  
   //-- load is 1
   if (load == 1'b1)
     qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module vf92dfc #(
 parameter v42e61f = 0
) (
 input vfde3d7,
 input vd9601b,
 output v157a67,
 output v64879c
);
 localparam p4 = v42e61f;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w5;
 wire w6;
 assign w0 = vd9601b;
 assign v157a67 = w1;
 assign v64879c = w3;
 assign w5 = vfde3d7;
 assign w6 = vfde3d7;
 assign w2 = w1;
 assign w6 = w5;
 vae13be vce6c1d (
  .ve78ab8(w2),
  .v3487af(w3),
  .ved8395(w6)
 );
 v2c0bd3 #(
  .v803182(p4)
 ) v7bdcb1 (
  .v27dec4(w0),
  .v4642b6(w1),
  .v25ab12(w5)
 );
endmodule

//---------------------------------------------------
//-- Button-tic_ECP5
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Button-tic: Configurable button that emits a tic when it is pressed. ECP5 FPGA Family
//---------------------------------------------------
//---- Top entity
module vae13be (
 input ved8395,
 input ve78ab8,
 output v1c9ba2,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign w4 = ve78ab8;
 assign v3487af = w5;
 assign w4 = w0;
 v3676a0 v9d4cda (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
 vba518e v57aa83 (
  .v0e28cb(w3),
  .v3ca442(w4),
  .vcbab45(w5)
 );
 v58ed2b v4953b3 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w2)
 );
endmodule

//---------------------------------------------------
//-- Rising-edge-detector
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Rising-edge detector. It generates a 1-period pulse (tic) when a rising edge is detected on the input. Block implementation
//---------------------------------------------------
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module v2c0bd3 #(
 parameter v803182 = 0
) (
 input v25ab12,
 input v27dec4,
 output v4642b6
);
 localparam p1 = v803182;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign v4642b6 = w3;
 assign w4 = v27dec4;
 assign w5 = v25ab12;
 assign w6 = v25ab12;
 assign w6 = w5;
 vad96dc #(
  .v6a9fe4(p1)
 ) vc0a9e9 (
  .v27dec4(w0),
  .v4642b6(w2)
 );
 vdd36dc v6e12f3 (
  .v6a82dd(w2),
  .vd4e5d7(w3),
  .v444878(w6)
 );
 v0705a6 v968074 (
  .v3c12b5(w0),
  .ve7f5e6(w4),
  .v717e81(w5)
 );
endmodule

//---------------------------------------------------
//-- Button_ECP5
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Configurable button (pull-up on/off. Not on/off). ECP5 FPGA family
//---------------------------------------------------
//---- Top entity
module vad96dc #(
 parameter v6a9fe4 = 0
) (
 input v27dec4,
 output v4642b6
);
 localparam p0 = v6a9fe4;
 wire w1;
 wire w2;
 wire w3;
 assign w2 = v27dec4;
 assign v4642b6 = w3;
 vd12401 v5b01c7 (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w3)
 );
 v6b14d5 #(
  .vc5c8ea(p0)
 ) v94e17e (
  .v268bfc(w1)
 );
endmodule

//---------------------------------------------------
//-- not-wire-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Select positive or negative logic for the input (0=positive, 1=negative)
//---------------------------------------------------
//---- Top entity
module v6b14d5 #(
 parameter vc5c8ea = 0
) (
 output v268bfc
);
 localparam p0 = vc5c8ea;
 wire w1;
 assign v268bfc = w1;
 v6b14d5_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 1-bit-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 1-bit generic constant (0/1)
//---------------------------------------------------

module v6b14d5_v465065 #(
 parameter VALUE = 0
) (
 output k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vdd36dc (
 input v444878,
 input v6a82dd,
 output vd4e5d7
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign w2 = v444878;
 assign w3 = v444878;
 assign w4 = v444878;
 assign vd4e5d7 = w5;
 assign w6 = v6a82dd;
 assign w7 = v6a82dd;
 assign w3 = w2;
 assign w4 = w2;
 assign w4 = w3;
 assign w7 = w6;
 v1ed41a vd680b8 (
  .v3487af(w1),
  .ved8395(w4),
  .ve78ab8(w7)
 );
 v8a23ff v02f115 (
  .vd793aa(w0),
  .ve4a668(w2),
  .v4642b6(w5),
  .v27dec4(w6)
 );
 ve8e3e6 vc4d90e (
  .ve37344(w0),
  .ve556f1(w1),
  .v6dda25(w3)
 );
endmodule

//---------------------------------------------------
//-- Debouncer-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Remove the rebound on a mechanical switch
//---------------------------------------------------
//---- Top entity
module v1ed41a (
 input ved8395,
 input ve78ab8,
 output v31351e,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign v3487af = w2;
 assign w4 = ve78ab8;
 assign w4 = w0;
 vd12401 v456da5 (
  .vcbab45(w2),
  .v0e28cb(w3),
  .v3ca442(w4)
 );
 v58ed2b vf94974 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w3)
 );
endmodule

//---------------------------------------------------
//-- Edges-detector-block
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Edges detector. It generates a 1-period pulse (tic) when either a rising edge or a falling edge is detected on the input. Block implementation
//---------------------------------------------------
//---- Top entity
module v8a23ff #(
 parameter v3360b0 = 0
) (
 input ve4a668,
 input v27dec4,
 input vd793aa,
 output v4642b6
);
 localparam p4 = v3360b0;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = ve4a668;
 assign w1 = v27dec4;
 assign w2 = vd793aa;
 assign v4642b6 = w3;
 v8a23ff_vb79aca #(
  .INI(p4)
 ) vb79aca (
  .clk(w0),
  .d(w1),
  .load(w2),
  .q(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF. D Flip-flop. Verilog implementation
//---------------------------------------------------

module v8a23ff_vb79aca #(
 parameter INI = 0
) (
 input clk,
 input d,
 input load,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 always @(posedge clk)
 begin
  
  //-- When load is active
  //-- the input data is captured
  if (load == 1'b1)
    qi <= d;
  
 end
 
 //-- Connect the register with the
 //-- output
 assign q = qi;
 
endmodule
//---- Top entity
module ve8e3e6 (
 input v6dda25,
 input ve556f1,
 output [15:0] v49911e,
 output ve37344
);
 wire w0;
 wire [0:15] w1;
 wire [0:15] w2;
 wire w3;
 wire [0:15] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v49911e = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 v8ecd59 v9392cd (
  .v2f9d57(w1),
  .vd7988b(w2),
  .v4642b6(w5)
 );
 v0788ea vd23000 (
  .v7bb757(w0),
  .ve56ffc(w1),
  .v76e2d3(w2),
  .v02833d(w3)
 );
endmodule

//---------------------------------------------------
//-- syscounter-rst-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 16-bits Syscounter with reset
//---------------------------------------------------
//---- Top entity
module v8ecd59 #(
 parameter v6c5139 = 1
) (
 input [15:0] v2f9d57,
 output v4642b6,
 output [15:0] vd7988b
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 assign v4642b6 = w0;
 assign w2 = v2f9d57;
 assign vd7988b = w3;
 v265696 #(
  .vd73390(p1)
 ) v76123a (
  .v4642b6(w0),
  .v36f2dd(w2),
  .vc068fb(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-16bit: Increment a 16-bits number by one
//---------------------------------------------------
//---- Top entity
module v265696 #(
 parameter vd73390 = 0
) (
 input [15:0] v36f2dd,
 output v4642b6,
 output [15:0] vc068fb
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 assign v4642b6 = w0;
 assign w3 = v36f2dd;
 assign vc068fb = w4;
 v651fa3 #(
  .vc5c8ea(p1)
 ) vdd8fa2 (
  .vcd9338(w2)
 );
 vbc66d7 vce7ab7 (
  .v4642b6(w0),
  .v1489e0(w2),
  .v603a9a(w3),
  .v2c4251(w4)
 );
endmodule

//---------------------------------------------------
//-- AdderK-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-16bit: Adder of 16-bit operand and 16-bit constant
//---------------------------------------------------
//---- Top entity
module v651fa3 #(
 parameter vc5c8ea = 0
) (
 output [15:0] vcd9338
);
 localparam p0 = vc5c8ea;
 wire [0:15] w1;
 assign vcd9338 = w1;
 v651fa3_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 16-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 16-bits generic constant
//---------------------------------------------------

module v651fa3_v465065 #(
 parameter VALUE = 0
) (
 output [15:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vbc66d7 (
 input [15:0] v1489e0,
 input [15:0] v603a9a,
 output v4642b6,
 output [15:0] v2c4251
);
 wire w0;
 wire w1;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 assign v4642b6 = w0;
 assign w2 = v603a9a;
 assign w3 = v1489e0;
 assign v2c4251 = w4;
 v306ca3 v0a29fe (
  .v91b9c1(w2),
  .vef5eee(w9),
  .vd3ef3b(w10)
 );
 v306ca3 vb0a6ce (
  .v91b9c1(w3),
  .vef5eee(w7),
  .vd3ef3b(w8)
 );
 vcb23aa v8e0bba (
  .v4642b6(w1),
  .v62bf25(w6),
  .v39966a(w8),
  .veb2f59(w10)
 );
 vc3c498 v917bbf (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .veeaa8e(w5),
  .v45c6ee(w7),
  .v20212e(w9)
 );
 v8cc49c v03c3e3 (
  .v14a530(w4),
  .vb334ae(w5),
  .v2b8a97(w6)
 );
endmodule

//---------------------------------------------------
//-- Adder-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-16bits: Adder of two operands of 16 bits
//---------------------------------------------------
//---- Top entity
module v306ca3 (
 input [15:0] v91b9c1,
 output [7:0] vef5eee,
 output [7:0] vd3ef3b
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v91b9c1;
 assign vef5eee = w1;
 assign vd3ef3b = w2;
 v306ca3_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-half: Split the 16-bits bus into two buses of the same size
//---------------------------------------------------

module v306ca3_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vcb23aa (
 input [7:0] v39966a,
 input [7:0] veb2f59,
 output v4642b6,
 output [7:0] v62bf25
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 assign w0 = veb2f59;
 assign w1 = v39966a;
 assign v62bf25 = w4;
 assign v4642b6 = w5;
 v6bdcd9 vd88c66 (
  .vcc8c7c(w0),
  .v651522(w9),
  .v2cc41f(w10)
 );
 v6bdcd9 v26a0bb (
  .vcc8c7c(w1),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v25966b v9ea427 (
  .v817794(w3),
  .v4642b6(w6),
  .v0550b6(w8),
  .v24708e(w10)
 );
 vafb28f vc75346 (
  .v515fe7(w2),
  .v3c88fc(w3),
  .va9ac17(w4)
 );
 va1ce30 v40c17f (
  .v817794(w2),
  .v4642b6(w5),
  .vb9cfc3(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
endmodule

//---------------------------------------------------
//-- Adder-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-8bits: Adder of two operands of 8 bits
//---------------------------------------------------
//---- Top entity
module v6bdcd9 (
 input [7:0] vcc8c7c,
 output [3:0] v651522,
 output [3:0] v2cc41f
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign v651522 = w0;
 assign v2cc41f = w1;
 assign w2 = vcc8c7c;
 v6bdcd9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Split-half: Split the 8-bits bus into two buses of the same size
//---------------------------------------------------

module v6bdcd9_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

//---------------------------------------------------
//-- Adder-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-4bits: Adder of two operands of 4 bits
//---------------------------------------------------
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module vafb28f (
 input [3:0] v515fe7,
 input [3:0] v3c88fc,
 output [7:0] va9ac17
);
 wire [0:7] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign va9ac17 = w0;
 assign w1 = v515fe7;
 assign w2 = v3c88fc;
 vafb28f_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Join-half: Join the two same halves into an 8-bits Bus
//---------------------------------------------------

module vafb28f_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va1ce30 (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 input vb9cfc3,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 assign w11 = vb9cfc3;
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w13),
  .v82de4f(w17)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w14),
  .vda577d(w17),
  .v3f8943(w18),
  .v64d863(w19)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b v3599be (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v0ef266(w11),
  .v27dec4(w16),
  .v82de4f(w19)
 );
endmodule

//---------------------------------------------------
//-- AdderC-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-4bits: Adder of two operands of 4 bits and Carry in
//---------------------------------------------------
//---- Top entity
module vc3c498 (
 input [7:0] v45c6ee,
 input [7:0] v20212e,
 input vb9cfc3,
 output v4642b6,
 output [7:0] veeaa8e
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 wire [0:3] w11;
 assign w1 = vb9cfc3;
 assign w2 = v45c6ee;
 assign w3 = v20212e;
 assign veeaa8e = w4;
 assign v4642b6 = w7;
 v6bdcd9 v8d795a (
  .vcc8c7c(w3),
  .v651522(w10),
  .v2cc41f(w11)
 );
 v6bdcd9 v23dbc5 (
  .vcc8c7c(w2),
  .v651522(w8),
  .v2cc41f(w9)
 );
 vafb28f vef3a58 (
  .va9ac17(w4),
  .v3c88fc(w5),
  .v515fe7(w6)
 );
 va1ce30 v0ff71a (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .v817794(w5),
  .v0550b6(w9),
  .v24708e(w11)
 );
 va1ce30 v12f94f (
  .vb9cfc3(w0),
  .v817794(w6),
  .v4642b6(w7),
  .v0550b6(w8),
  .v24708e(w10)
 );
endmodule

//---------------------------------------------------
//-- AdderC-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-8bits: Adder of two operands of 8 bits and Carry in
//---------------------------------------------------
//---- Top entity
module v8cc49c (
 input [7:0] vb334ae,
 input [7:0] v2b8a97,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v14a530 = w0;
 assign w1 = v2b8a97;
 assign w2 = vb334ae;
 v8cc49c_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-half: Join the two same halves into an 16-bits Bus
//---------------------------------------------------

module v8cc49c_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v0788ea #(
 parameter vdb1a33 = 0
) (
 input v02833d,
 input v7bb757,
 input [15:0] v76e2d3,
 output v24626e,
 output v713f73,
 output [15:0] ve56ffc
);
 localparam p1 = vdb1a33;
 wire [0:15] w0;
 wire w2;
 wire [0:15] w3;
 wire w4;
 assign ve56ffc = w0;
 assign w2 = v7bb757;
 assign w3 = v76e2d3;
 assign w4 = v02833d;
 v0788ea_v22c6dc #(
  .INI(p1)
 ) v22c6dc (
  .q(w0),
  .rst(w2),
  .d(w3),
  .clk(w4)
 );
endmodule

//---------------------------------------------------
//-- 16-Sys-reg-rst
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 16-Sys-reg-rst: 16 bits system register with reset. Verilog implementation
//---------------------------------------------------

module v0788ea_v22c6dc #(
 parameter INI = 0
) (
 input clk,
 input rst,
 input [15:0] d,
 output [15:0] q
);
 //-- Generic System register
 //-- with reset
 //-- Number of bits
 localparam N = 16;
 
 //-- Initial value
 reg [N-1:0] qi = INI;
 
 always @(posedge clk)
 begin
 
   //-- Reset: Capture the initial
   //-- value
   if (rst == 1'b1)
     qi <= INI;
     
   //-- No reset: Capture the input
   else
     qi <= d;
 end
 
 //-- Connect the register with the
 //-- output
 assign q = qi;
 
endmodule
//---- Top entity
module v0705a6 (
 input v717e81,
 input ve7f5e6,
 output v994965,
 output v3c12b5
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v717e81;
 assign w1 = ve7f5e6;
 assign v3c12b5 = w2;
 v0705a6_ve03af9 ve03af9 (
  .clk(w0),
  .d(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- Sync-x01-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Sync-x01: 1-bit input with the system clock domain (Verilog implementation)
//---------------------------------------------------

module v0705a6_ve03af9 (
 input clk,
 input d,
 output q
);
 //-- Two D flip-flops
 //-- connected in cascade
 
 reg q1 = 0;
 reg q2 = 0;
 
 always @(posedge clk) 
 begin
   //-- First D Flip-Flop
   q1 <= d;
   
   //-- Secondo D Flip-flop
   q2 <= q1;
 end
 
 //-- Assign the output
 assign q = q2;
endmodule
