// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 output v0658ae,
 output [0:6] vinit
);
 wire w0;
 assign v0658ae = w0;
 vfebcfe v8f07dd (
  .v9fb85f(w0)
 );
 assign vinit = 7'b0000000;
endmodule

//---------------------------------------------------
//-- Led on
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
