// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input vfd81f6,
 input v3e4864,
 output vbebc54,
 output va5a5ae,
 output [0:5] vinit
);
 wire w0;
 wire w1;
 assign w0 = vfd81f6;
 assign vbebc54 = w0;
 assign w1 = v3e4864;
 assign va5a5ae = w1;
 assign vinit = 6'b000000;
endmodule

