// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 output v78cf31,
 output vbf4249,
 output v0ed968,
 output v20462a,
 output v543161,
 output v265576,
 output vae30eb,
 output v7a26f9
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign v78cf31 = w0;
 assign vbf4249 = w1;
 assign v0ed968 = w2;
 assign v20462a = w3;
 assign v543161 = w4;
 assign v265576 = w5;
 assign vae30eb = w6;
 assign v7a26f9 = w7;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w3 = w0;
 assign w3 = w1;
 assign w3 = w2;
 assign w5 = w4;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 vfebcfe v6d3368 (
  .v9fb85f(w0)
 );
 vfebcfe vc498f8 (
  .v9fb85f(w4)
 );
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
